+define+SYNTHESIS
+define+XIANGSHAN_FPGA
+define+RANDOMIZE_GARBAGE_ASSIGN
+define+RANDOMIZE_REG_INIT
+define+RANDOMIZE_MEM_INIT
+define+RANDOMIZE_DELAY=1
+define+UVHS_SOC_ADAPT
+define+UVHS_NO_XILINX_CLK_PRIMS
+define+DDR4_16G_X8
+define+DQ64
+define+DDR4_2400
+define+DQ=64
+define+MICRON_DDR
+define+DDR4_16Gbx8
+define+DDR4
+define+SRAM_SYN
+define+DATA_VERSION=0
+define+CPU_NUTSHELL
+define+UVHS_EXTERNAL_UVW_AXI4_TO_DDR4
+define+UVHS_UVW_AXI4_TO_DDR4
+define+CONFIG_USE_XSCORE_AXI
+incdir+vendor/platform
+incdir+vendor/cpu
+incdir+vendor/cpu/generated-src
vendor/platform/RST_SYNC.v
vendor/platform/button_debounce.v
rtl/core_def_xdma.sv
rtl/fpga_top_debug.sv
vendor/platform/jtag_ddr_subsys_wrapper.v
vendor/platform/mode_ctrl.v
vendor/platform/pcie_rc_subsys_wrapper.v
vendor/platform/sys_define.vh
vendor/platform/syscfg.v
vendor/platform/syscfg_define.v
vendor/platform/uvhs_axi64_to_axi256.sv
vendor/platform/uvhs_axi_to_mem_array.sv
vendor/platform/uvhs_axilite_cdc_bridge.sv
vendor/platform/uvhs_blackbox_stubs.v
vendor/platform/uvhs_cpu_liveness_gbd.sv
vendor/platform/xilnx_crg.v
vendor/cpu/SimTop_wrapper.sv
vendor/cpu/generated-src/DifftestMacros.svh
vendor/cpu/rtl/ALU.sv
vendor/cpu/rtl/AXI42SimpleBusConverter.sv
vendor/cpu/rtl/AXI4CLINT.sv
vendor/cpu/rtl/AXI4PLIC.sv
vendor/cpu/rtl/Arbiter1_SRAMBundleA.sv
vendor/cpu/rtl/Arbiter1_SRAMBundleA_2.sv
vendor/cpu/rtl/Arbiter1_SimpleBusReqBundle.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleA.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleAW.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleAW_1.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleAW_4.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleAW_5.sv
vendor/cpu/rtl/Arbiter2_SRAMBundleA_2.sv
vendor/cpu/rtl/Arbiter2_SimpleBusReqBundle.sv
vendor/cpu/rtl/AsyncClockFIFO.sv
vendor/cpu/rtl/AsyncClockFIFO_1.sv
vendor/cpu/rtl/AtomALU.sv
vendor/cpu/rtl/BPU_inorder.sv
vendor/cpu/rtl/Backend_inorder.sv
vendor/cpu/rtl/BatchCluster.sv
vendor/cpu/rtl/BatchCluster_1.sv
vendor/cpu/rtl/BatchCluster_2.sv
vendor/cpu/rtl/BatchCluster_3.sv
vendor/cpu/rtl/BatchCluster_4.sv
vendor/cpu/rtl/BatchCluster_5.sv
vendor/cpu/rtl/BatchCollector.sv
vendor/cpu/rtl/BatchEndpoint.sv
vendor/cpu/rtl/CSR.sv
vendor/cpu/rtl/CSRDiffWrapper.sv
vendor/cpu/rtl/Cache.sv
vendor/cpu/rtl/CacheStage1.sv
vendor/cpu/rtl/CacheStage1_1.sv
vendor/cpu/rtl/CacheStage1_2.sv
vendor/cpu/rtl/CacheStage2.sv
vendor/cpu/rtl/CacheStage2_1.sv
vendor/cpu/rtl/CacheStage2_2.sv
vendor/cpu/rtl/CacheStage3.sv
vendor/cpu/rtl/CacheStage3_1.sv
vendor/cpu/rtl/CacheStage3_2.sv
vendor/cpu/rtl/Cache_1.sv
vendor/cpu/rtl/Cache_2.sv
vendor/cpu/rtl/CoherenceManager.sv
vendor/cpu/rtl/Decoder.sv
vendor/cpu/rtl/DelayReg.sv
vendor/cpu/rtl/DelayReg_1.sv
vendor/cpu/rtl/DeltaEndpoint.sv
vendor/cpu/rtl/DeltaSplitter.sv
vendor/cpu/rtl/DeltaSplitter_1.sv
vendor/cpu/rtl/DiffExtBatch.v
vendor/cpu/rtl/Difftest2AXIs.sv
vendor/cpu/rtl/DifftestMemCtrl.sv
vendor/cpu/rtl/DifftestResetSync.v
vendor/cpu/rtl/Divider.sv
vendor/cpu/rtl/DummyDPICBatchWrapper.sv
vendor/cpu/rtl/EXU.sv
vendor/cpu/rtl/EmbeddedTLB.sv
vendor/cpu/rtl/EmbeddedTLBEmpty_1.sv
vendor/cpu/rtl/EmbeddedTLBExec.sv
vendor/cpu/rtl/EmbeddedTLBExec_1.sv
vendor/cpu/rtl/EmbeddedTLBMD.sv
vendor/cpu/rtl/EmbeddedTLBMD_1.sv
vendor/cpu/rtl/EmbeddedTLB_1.sv
vendor/cpu/rtl/FlushableQueue.sv
vendor/cpu/rtl/Frontend_inorder.sv
vendor/cpu/rtl/GatewayEndpoint.sv
vendor/cpu/rtl/H2CAXIs2Mem.sv
vendor/cpu/rtl/HostEndpoint.sv
vendor/cpu/rtl/IDU.sv
vendor/cpu/rtl/IFU_inorder.sv
vendor/cpu/rtl/ISU.sv
vendor/cpu/rtl/LSExecUnit.sv
vendor/cpu/rtl/LockingArbiter.sv
vendor/cpu/rtl/LockingArbiter_1.sv
vendor/cpu/rtl/MDU.sv
vendor/cpu/rtl/MOU.sv
vendor/cpu/rtl/Multiplier.sv
vendor/cpu/rtl/NaiveRVCAlignBuffer.sv
vendor/cpu/rtl/NutCore.sv
vendor/cpu/rtl/NutShell.sv
vendor/cpu/rtl/Prefetcher.sv
vendor/cpu/rtl/PreprocessEndpoint.sv
vendor/cpu/rtl/SRAMTemplate.sv
vendor/cpu/rtl/SRAMTemplateWithArbiter.sv
vendor/cpu/rtl/SRAMTemplateWithArbiter_1.sv
vendor/cpu/rtl/SRAMTemplateWithArbiter_4.sv
vendor/cpu/rtl/SRAMTemplateWithArbiter_5.sv
vendor/cpu/rtl/SRAMTemplate_1.sv
vendor/cpu/rtl/SRAMTemplate_2.sv
vendor/cpu/rtl/SRAMTemplate_5.sv
vendor/cpu/rtl/SRAMTemplate_6.sv
vendor/cpu/rtl/SimpleBus2AXI4Converter.sv
vendor/cpu/rtl/SimpleBus2AXI4Converter_1.sv
vendor/cpu/rtl/SimpleBus2AXI4Converter_2.sv
vendor/cpu/rtl/SimpleBusAddressMapper.sv
vendor/cpu/rtl/SimpleBusCrossbar1toN.sv
vendor/cpu/rtl/SimpleBusCrossbarNto1.sv
vendor/cpu/rtl/SimpleBusCrossbarNto1_1.sv
vendor/cpu/rtl/SquashControl.v
vendor/cpu/rtl/SquashEndpoint.sv
vendor/cpu/rtl/Squasher.sv
vendor/cpu/rtl/Squasher_1.sv
vendor/cpu/rtl/Squasher_2.sv
vendor/cpu/rtl/Squasher_3.sv
vendor/cpu/rtl/Squasher_4.sv
vendor/cpu/rtl/Stamper.sv
vendor/cpu/rtl/TopMain.sv
vendor/cpu/rtl/UnpipelinedLSU.sv
vendor/cpu/rtl/Validator.sv
vendor/cpu/rtl/WBU.sv
vendor/cpu/rtl/XDMAConfigBar.sv
vendor/cpu/rtl/array_1024x256.sv
vendor/cpu/rtl/array_128x84.sv
vendor/cpu/rtl/array_4096x256.sv
vendor/cpu/rtl/array_512x73.sv
vendor/cpu/rtl/array_512x76.sv
vendor/cpu/rtl/fifo_banks_16x256.sv
vendor/cpu/rtl/memBanks_16x256.sv
vendor/cpu/rtl/mem_32x256.sv
vendor/cpu/rtl/mem_32x289.sv
vendor/cpu/rtl/pht_512x2.sv
vendor/cpu/rtl/ram_4x147.sv
vendor/cpu/rtl/ras_16x39.sv
vendor/cpu/rtl/rf_32x64.sv
